BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Preguntas" (
	"id_pregunta"	INTEGER NOT NULL,
	"contenido"	TEXT NOT NULL,
	"tema"	TEXT NOT NULL,
	"dificultad"	NUMERIC NOT NULL,
	"dato"	TEXT NOT NULL,
	PRIMARY KEY("id_pregunta" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Usuarios" (
	"id_usuario"	INTEGER NOT NULL,
	"nombre"	TEXT NOT NULL,
	"tiempo"	TEXT NOT NULL,
	"puntaje"	INTEGER NOT NULL,
	PRIMARY KEY("id_usuario" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Respuestas" (
	"id_respuesta"	INTEGER NOT NULL,
	"id_pregunta"	INTEGER,
	"contenido"	TEXT NOT NULL,
	"correcta"	BLOB NOT NULL,
	FOREIGN KEY("id_pregunta") REFERENCES "Preguntas"("id_pregunta"),
	PRIMARY KEY("id_respuesta" AUTOINCREMENT)
);
INSERT INTO "Preguntas" VALUES (1,'¿Cuál es el rol que cumple un Maestro Psicólogo Orientador (MPO)?
','educacion',1,'Su práctica la desarrollan docentes psicólogos o psicopedagogos que brindan apoyo a alumnos/as que transitan su trayectoria escolar en los CENTES y que se encuentran en proceso de inclusión en escuelas de los diferentes niveles del sistema educativo. Asimismo, su intervención también se le brinda a aquellos niños/as que necesiten acompañamiento.');
INSERT INTO "Preguntas" VALUES (2,'Entre 2019 y 2020, se registró que hay un mayor índice de mujeres universitarias registradas en:','educacion',1,'En cuanto a las ramas de estudio, se observa que la mayor cantidad de mujeres elige las ciencias sociales (484.322), humanas (287.452) y de la salud (283.767). Muy por debajo se ubican las ciencias básicas (34.217) pero que a pesar de su baja matrícula, cuentan con un 61% de participación femenina. La menor incidencia de las mujeres se da en las ciencias aplicadas, que representan el 37,3% del alumnado.');
INSERT INTO "Preguntas" VALUES (3,'¿Cómo se ve reflejada la desigualdad dentro del ambiente escolar?','educacion',1,'La mayoría de las escuelas que mantienen una educación con un claro predominio de lo masculino y poca presencia de las mujeres tanto en los contenidos académicos como en las enseñanzas que no se ven pero se aprenden: las conversaciones, el uso de los espacios, el lenguaje, los ejemplos, las fiestas de fin de curso, la educación emocional, las canciones, las manualidades para el día del padre y de la madre. ');
INSERT INTO "Preguntas" VALUES (4,'La desigualdad educativa se debe a…','educacion',1,'La igualdad (o desigualdad) educativa puede referirse a las oportunidades de acceso, a la permanencia, al egreso o incluso al nivel de aprendizaje. Esto último es, por supuesto, lo más interesante, pero también lo más difícil de medir. Por ello, el estudio de la igualdad (o desigualdad) educativa suele limitarse a los años de escolaridad alcanzados.');
INSERT INTO "Preguntas" VALUES (5,'Un estudio reveló que únicamente 3 de cada 10 personas de sectores vulnerables terminan el secundario en Argentina. Esto se debe a…','educacion',1,'En el mismo, los resultados demuestran que un 98% tiene el primario completo, un 87% el secundario completo, un 51% el universitario, y un 6,5% el posgrado. Esos valores son con respecto a aquellos que pertenecen al decil de ingreso per cápita más alto. A diferencia de ello, el más bajo refleja un 89%, un 32%, un 2% y un 0% respectivamente.');
INSERT INTO "Preguntas" VALUES (6,'Salario promedio mensual profesores de escuelas secundarias','educacion',2,'El sueldo de un profesor de nivel secundario es muy bajo en comparación con el resto de los profesionales, como por ejemplo el título de analista en sistemas o de ingeniería química.');
INSERT INTO "Preguntas" VALUES (7,'Dentro de los valores de gasto educativo jurisdiccional, en el año 2020 se registró un total de 82,3 mil millones de pesos. ¿Qué porcentaje crees que, dentro de las erogaciones corrientes, fue destinado para gastos personales?','educacion',2,'El total de gastos en educación registrado en 2020 es de 82,7 mil millones de pesos. Esta cifra se divide entre: erogaciones corrientes (que a su vez se clasifica entre personal, bienes y servicios no personales, y transferencias), otras erogaciones corrientes y erogaciones de capital.');
INSERT INTO "Preguntas" VALUES (8,'¿Cuántos días, dentro del calendario escolar, fueron destinados en 2018 como días de clases dentro de aula?','educacion',2,'Los chicos argentinos que van a la escuela primaria tienen menos tiempo de clase que la media internacional. Cuando el promedio de la OCDE es de 183 días de clase y 794 horas, en Argentina el calendario escolar estipula 180 días, lo que da un total de 720 horas dentro del aula.');
INSERT INTO "Preguntas" VALUES (9,'Aunque suene sorprendente, la educación en el ámbito rural alcanzó mejores porcentajes de nivel de estudios, en comparación con el nivel nacional. Teniendo en cuenta eso, ¿cuál sería el porcentaje de ciudadanos sin estudios en el promedio de la totalidad del país?','educacion',2,'En cuanto al nivel de estudio, en el ámbito rural, los porcentajes de personas sin estudios es de 1%, de primaria incompleta de 5%, de primaria completa de 25%, de secundario incompleto de 11%, de secundario completo de 39%, de universitario de 18% y de posgrado de 1%. ');
INSERT INTO "Preguntas" VALUES (10,'¿Cuál sería el porcentaje de la tasa alfabetización de adultos en Argentina?','educacion',2,'El analfabeto no puede entender cuáles son sus derechos, debido a lo cual es marginado por la sociedad. Esto también es motivo para aprovecharse de su ignorancia y explotarlo. Si bien los analfabetos viven lejos de una sociedad "civilizada", este problema hace que se mantengan como tal, cerrando las puertas a diversas oportunidades en una vida futura.');
INSERT INTO "Preguntas" VALUES (11,'Durante la pandemia por COVID-19 muchos estudiantes, de todos los niveles, no pudieron tener una continuidad de sus tareas escolares debido a la virtualidad. ¿Cuáles son los factores que causaron esta brecha?','educacion',2,'La desigualdad escolar se replica y se intensifica durante tiempos de pandemia. Existen diversas variables que afectan la continuidad educativa mediante la educación virtual: el tiempo disponible de los padres para ayudar a sus hijos, la tecnología existente en los hogares, los recursos pedagógicos de los docentes, las posibilidades de las escuelas, etc.');
INSERT INTO "Preguntas" VALUES (12,'La deserción escolar acentuada por la pandemia por coronavirus tiene diversas causas, como por ejemplo el entorno familiar y la falta de acceso a internet. Sin embargo, hay una de ellas (aún no mencionada) que no es tan reconocida por los docentes. ¿Cuál es?','educacion',2,'Desde el inicio de la cuarentena obligatoria creció notablemente la cantidad de estudiantes (y familiares de ellos) con depresión y ansiedad. Esto tiene diversas y variadas causas, como por ejemplo el encierro, la falta de actividad social, y el miedo a contagiarse del virus.');
INSERT INTO "Preguntas" VALUES (13,'¿En qué año fue sancionada la Ley de Educación Nacional en Argentina?','educacion',2,'Esta Ley tiene el objetivo de regular el cumplimiento del derecho de enseñar y aprender, el cual se encuentra vigente en el artículo 14 de la Constitución Nacional, y respaldado por los tratados internacionales que fueron incorporados en ella. ');
INSERT INTO "Preguntas" VALUES (14,'¿Cuándo fue sancionada la Ley de Educación Sexual Integral?','educacion',2,'Esta ley tiene como objetivos principales incorporar la ESI de forma armónica, equilibrada y permanente, y procurar igualdad de oportunidades y de trato para todos los géneros y sectores sociales.');
INSERT INTO "Preguntas" VALUES (15,'¿Cuántos dispositivos electrónicos fueron entregados a través del Programa Conectar Igualdad para aumentar la regularidad en la escuela secundaria?','educacion',2,'"A través de Conectar Escuelas buscamos garantizar el servicio de internet en las aulas y su disponibilidad para todas las escuelas de gestión estatal. Nuestro objetivo es alcanzar el 90% de las y los estudiantes del país al finalizar el presente ciclo lectivo".');
INSERT INTO "Preguntas" VALUES (16,'¿Cuál es el país con más discriminación por color de piel en América Latina?','etnia',1,'A partir de los datos recolectados en una encuesta realizada por la Corporación Latinobarómetro en 18 países latinoamericanos a fines de 2020, vemos que Brasil es donde más encuestados designan a las personas negras como las más discriminadas, con más del 52%, seguido de Colombia, con un 17% de las respuestas, y Uruguay, con el 15%.');
INSERT INTO "Preguntas" VALUES (17,'Señale los tipos de discriminacion racial.','etnia',1,'El hostigador puede ser tu supervisor, un supervisor de otra área, un compañero o alguien que no trabaja para tu patrono, como un cliente. El hostigamiento racial puede incluir calumnias raciales, chistes o comentarios, dibujos, caricaturas, símbolos o gestos ofensivos con respecto a la raza y otras conductas físicas o verbales basadas en la raza de un individuo.');
INSERT INTO "Preguntas" VALUES (18,'¿Comentar sobre cuáles de los siguientes aspectos no se considera disriminación racial?','etnia',1,'La discriminación y el racismo es cualquier trato diferenciado que se base en motivos como características físicas (o fenotípicas como el color y tipo de piel o cabello, facciones, estatura, entre otros) y étnico-culturales (lengua materna, acento o dejo, costumbres, indumentaria, símbolos, creencias y otras prácticas culturales o formas de vida, identificación y pertenencia a un grupo étnico o cultural). ');
INSERT INTO "Preguntas" VALUES (19,'¿Cuál de las siguientes opciones no son acciones que contribuyen a frenar la discriminacion por etnia?','etnia',1,'Presta atención a las personas que enfrentan el racismo a diario. Hay muchos artículos, libros, documentales, películas y podcasts relacionados con el racismo, discriminación y privilegios. Escucha lo que dicen quienes aparecen en ellos. Comprende y confronta tu propio privilegio.');
INSERT INTO "Preguntas" VALUES (20,'¿Cómo mostrar respetuosamente tu desacuerdo?','etnia',1,'Por supuesto, el respeto no sólo debe tenerse en cuenta en las conversaciones difíciles. Ser amable y considerado con los miembros de tu familia, profesores o consejeros escolares en las actividades cotidianas nos ayudará a sentar las bases para los momentos en que podamos no estar de acuerdo.');
INSERT INTO "Preguntas" VALUES (21,'¿Cuándo se celebra el Día del Respeto a la Diversidad Cultural 2022 (Argentina)?','etnia',2,'Este día nos invita a reivindicar el diálogo, intercambio y respeto entre las distintas culturas que conviven en nuestro país, hagamos que la riqueza de nuestras raíces siga haciendo grande a nuestro país.');
INSERT INTO "Preguntas" VALUES (22,'¿Cuándo se celebra el Día Mundial de la Diversidad Cultural para el Diálogo y el Desarrollo propuesta por la ONU?','etnia',2,'En el año 2003, la Asamblea General de las Naciones Unidas decidió celebrar el Día Mundial de la Diversidad Cultural para el Diálogo y el Desarrollo con el objetivo de apoyar la diversidad, el diálogo, la inclusión y la cooperación entre las distintas culturas.');
INSERT INTO "Preguntas" VALUES (23,'¿Cuál era el nombre con el que se conocía el “Día del Respeto a la Diversidad Cultural” antes de su modificación en 2010?','etnia',2,'Hasta 2010 la fecha fue conocida como el “Día de la Raza” y conmemoraba la llegada de Cristóbal Colón a América. Sin embargo, en 2010, en nuestro país, cambia su denominación por la del “Día del Respeto a la Diversidad Cultural”, dotándolo de un significado acorde al valor que asigna nuestra Constitución Nacional y diversos tratados y declaraciones de derechos humanos a la diversidad étnica y cultural de todos los pueblos.');
INSERT INTO "Preguntas" VALUES (24,'¿Cuál fue la mayor acción tomada por las personas que sufrieron discriminacion en Argentina?','etnia',2,'Todas las personas que fueron discriminadas, hicieron algo al respecto. Solo el 7% denunció a las personas que los discriminaron. La mayor parte de los argentinos decidieron hablar con quienes los discriminan (36.8%), mientras que un 26.3% insultó a aquellos que los discriminaron.');
INSERT INTO "Preguntas" VALUES (25,'¿Cuál es el país con índice de discriminación racial más alto?','etnia',2,'Estados unidos incremento un 182% en términos de discriminación racial, de acuerdo con el informe la Liga Antidifamación publicado en 2018. La situación se evidenció con la distribución masiva de folletos, volantes y anuncios publicitarios, destinados a plantar la llamada "Supremacía Blanca" en territorio estadounidense.');
INSERT INTO "Preguntas" VALUES (26,'¿Cuál es el porcentaje de discriminacion por color de piel en Argentina?','etnia',2,'Una de cada tres personas se ha sentido discriminada por su situación económica (34.1%). Le siguen en orden de mención la discriminación por aspecto físico (19.4%) y por la forma de pensar (13.6%). Luego se encuentran obesidad (12.5), ser mujer (9.2) y finalmente color de piel (8.8) siendo el sexto factor de discriminacion en nuestro país.');
INSERT INTO "Preguntas" VALUES (27,'¿Cuáles son los ámbitos en los que la discriminacion más se ve presente en Argentina?','etnia',2,'Los ámbitos educativos (27.1%) y laborales (24.9%) son los ámbitos de mayor discriminación, aunque una de cada tres personas no identifica un ámbito en particular en la que ha sido discriminada (34.1%). ');
INSERT INTO "Preguntas" VALUES (28,'¿Qué rango de edad es el más discriminado?','etnia',2,'Una de cada tres personas se ha sentido discriminada alguna vez. Las personas de menor edad fueron las que mencionaron en mayor porcentaje que fueron discriminadas. Entre las edades de 18 a 44 se encuentran un 76.3% de los discriminados.  ');
INSERT INTO "Preguntas" VALUES (29,'¿Cuántas personas presenciaron una situación en la que otro fue discriminado?','etnia',2,'Dos de cada tres personas presenciaron situaciones de discriminación. Los jóvenes de 18 a 29 años fueron quienes mayor cantidad de situaciones vivieron en la que otra persona fue discriminada.');
INSERT INTO "Preguntas" VALUES (30,'¿Cuál es la reacción más común frente a una situación de discriminacion racial de personas que presencian el hecho?','etnia',2,'Seis de cada diez personas que presenciaron discriminación indicaron que la reacción de las demás personas es de indiferencia frente al hecho. Un 15.3% realizan comentarios de reprobación y sólo 14.7% interviene directamente con el agresor. ');
INSERT INTO "Preguntas" VALUES (31,'¿En qué lugares se ve reflejada la desigualdad de géneros?','genero',1,'Las mujeres y las comunidades sexuales minoritarias (LGBT) son generalmente objeto de prácticas discriminatorias en el ámbito laboral, afectivo y social. Esto los hace más vulnerables a la discriminación y a la violencia de género. En este sentido, la desigualdad de género provoca una disminución en las oportunidades, aumentando las disparidades respecto a la vivienda, la seguridad y la salud.');
INSERT INTO "Preguntas" VALUES (32,'Debido a la división sexual del trabajo, se les asignó una serie de roles y trabajos (algunos no remunerados) a las mujeres, entre los cuales se encuentran…','genero',1,'Esta particular división del trabajo constituye un producto tanto histórico como humano y, por lo tanto, es factible de cambios que implican diversos aspectos de la vida cultural, social, económica, política, entre otras.');
INSERT INTO "Preguntas" VALUES (33,'¿En qué ambientes legislativos hay mayoría de hombres dentro de los puestos más importantes?','genero',1,'En el sector público, en el Gabinete nacional solo hay 2 ministras, en el Congreso todavía no se obtiene la paridad de género y en el Poder Judicial, las juezas designadas son minoría. En el sector privado, las mujeres que encabezan entidades como sociedades anónimas y asociaciones civiles no superan el 30% del total.');
INSERT INTO "Preguntas" VALUES (34,'¿Cuál es el Día Nacional de Las Amas de Casa?','genero',1,'El 1 de diciembre se celebra cada año el Día del Ama de Casa. La fecha se dispuso en 1958 y fue establecida por la Liga de Amas de Casa, una asociación que había sido creada un año antes para la defensa de las mujeres trabajadoras que llevaban adelante el cuidado de sus hogares.');
INSERT INTO "Preguntas" VALUES (35,'¿En qué artículo de la Constitución Argentina se establece la igualdad de oportunidades entre hombres y mujeres en cuanto a la participación en el régimen electoral?','genero',1,'En ambos artículos, se decreta la igualdad de ejercicios de derechos en forma igualitaria sin ningún tipo de discriminación. En el artículo 37, específicamente, se proclama la igualdad en cuanto al acceso a cargos electivos y partidarios, así como también se garantiza acciones afirmativas en la regulación de partidos políticos y el régimen electoral.');
INSERT INTO "Preguntas" VALUES (36,'¿Cuál es el país con menor índice de desigualdad de género?','genero',2,'En la edición de 2021, Islandia ocupa por duodécimo año consecutivo el primer puesto del ranking, siendo el país con mayor igualdad de género del mundo, con una puntuación de 0,892. El podio se completa con otros dos países nórdicos, Finlandia y Noruega.');
INSERT INTO "Preguntas" VALUES (37,'¿Cuál es el país con mayor índice de desigualdad de género?','genero',2,'Nigeria se coloca como el peor país en equidad de género. De acuerdo con el reporte de ONE, las niñas tienen 16 meses menos de educación que los niños, solo el 2.6% de las jóvenes de quince años en adelante tienen una cuenta bancaria, menos de la mitad tienen trabajos pagados y únicamente el 13% de los miembros del parlamento nacional son mujeres.');
INSERT INTO "Preguntas" VALUES (38,'¿Cuál es el porcentaje registrado (de mujeres) de población asalariada en condición de precariedad en 2019?','genero',2,'En comparación con el porcentaje de varones, el cual es de 24,5%, el promedio entre ambos alcanza un 26,8% de la población total de Argentina que se encontraba en condición de falta de sueldo por condición de precariedad en 2019.');
INSERT INTO "Preguntas" VALUES (39,'¿Cuál es el porcentaje de mujeres que tienen un cargo dentro de la dirección de empresas en 2018?','genero',2,'En 2016 se registró un 3,6%, al igual que en 2017; sin embargo, ya para el año 2018, este porcentaje creció un 0,1%.');
INSERT INTO "Preguntas" VALUES (40,'¿Cuál es la cifra de cambios registrados de género inscriptos en el Registro Civil en 2020?','genero',2,'Dentro del total de 96 cambios, 18 fueron de ciudadanos que corresponden al rango etario que va desde 5 a 17 años, y los otros 78 son de 18 en adelante.');
INSERT INTO "Preguntas" VALUES (41,'¿Cuál es el promedio de mujeres con secundario completo registrado en Argentina en el año 2020?','genero',2,'De un promedio total de 17,6%, las mujeres ocupan un 16,8% pero los hombres un 18,6%. Por otro lado, en cuanto al porcentaje de secundario incompleto con un promedio de 9,7%, los hombres las superan por un 3,5%. ');
INSERT INTO "Preguntas" VALUES (42,'¿Cuál es el porcentaje de mujeres en colegios técnicos en Argentina?','genero',2,'“La desigualdad en materia de género en la escuela técnica es un problema de larga data. Según datos del Instituto Nacional de Educación Tecnológica (INET), de cada 100 estudiantes de las secundarias técnicas argentinas, sólo 33 son mujeres.”');
INSERT INTO "Preguntas" VALUES (43,'¿Cuántas mujeres son amas de casa en Argentina?','genero',2,'Según datos de la Encuesta Permanente de Hogares, el 62% de las “inserciones laborales asociadas al cuidado” están ocupadas por mujeres, mientras que sólo el porcentaje restante, el 38%, están ocupadas por hombres.');
INSERT INTO "Preguntas" VALUES (44,'¿Cuál es el porcentaje de hombres que trabajan de maestro jardinero en Argentina?','genero',2,'A nivel nacional, en 2004 –los últimos datos sobre educación procesados–, sobre un total de 83.681 docentes de educación inicial había un 95,1% de mujeres y 4,9% de varones. Esto indica que, más de diez años después, hay por lo menos 4 mil varones que trabajan como maestros jardineros en todo el país.');
INSERT INTO "Preguntas" VALUES (45,'¿En qué año se decretó la creación del Consejo Federal para la prevención y el abordaje de femicidios, travesticidios y transfemicidios?','genero',2,'El Decreto 123/2021 fue creado con el objetivo de establecer un ámbito de trabajo interinstitucional de abordaje integral, eficaz y articulado que involucre a distintos organismos relacionados con el Estado Nacional.');
INSERT INTO "Usuarios" VALUES (1,'Martin','0003',10);
INSERT INTO "Respuestas" VALUES (1,1,'Es un docente psicólogo/psicopedagogo el cual brinda un apoyo dentro de la trayectoria escolar en centros especiales.
','True');
INSERT INTO "Respuestas" VALUES (2,1,'Es un docente capacitado para brindar una educación priorizada en niños con discapacidades o que necesitan un acompañamiento más personalizado.','False');
INSERT INTO "Respuestas" VALUES (3,1,'Es un docente capacitado el cual brinda un apoyo dentro de la trayectoria escolar en Centros Educativos para Niños con Tiempos y Espacios Singulares (CENTES).','False');
INSERT INTO "Respuestas" VALUES (4,1,'Es un docente psicólogo/psicopedagogo para brindar una educación priorizada en niños con discapacidades o que necesitan un acompañamiento más personalizado.','False');
INSERT INTO "Respuestas" VALUES (5,2,'Ciencias Sociales','False');
INSERT INTO "Respuestas" VALUES (6,2,'Ciencias Políticas','False');
INSERT INTO "Respuestas" VALUES (7,2,'Ingeniería Civil','False');
INSERT INTO "Respuestas" VALUES (8,2,'Ciencias Naturales, Matemáticas y Estadística','True');
INSERT INTO "Respuestas" VALUES (9,3,'Discriminación por no tener las mismas condiciones.','False');
INSERT INTO "Respuestas" VALUES (10,3,'Sentimiento de superioridad de género.','False');
INSERT INTO "Respuestas" VALUES (11,3,'Necesidad de trabajar a temprana edad, y por lo tanto un desequilibrio en los temarios preestablecidos de las distintas materias.','False');
INSERT INTO "Respuestas" VALUES (12,3,'Todas son correctas.','True');
INSERT INTO "Respuestas" VALUES (13,4,'Menor/mayor ingreso.','False');
INSERT INTO "Respuestas" VALUES (14,4,'Cantidad y calidad de insumos escolares.','False');
INSERT INTO "Respuestas" VALUES (15,4,'Nivel de aprendizaje alcanzado.','False');
INSERT INTO "Respuestas" VALUES (16,4,'Todas son correctas.','True');
INSERT INTO "Respuestas" VALUES (17,5,'Prioridad en la educación privada.','False');
INSERT INTO "Respuestas" VALUES (18,5,'Falta de predisposición de los estudiantes.','False');
INSERT INTO "Respuestas" VALUES (19,5,'Ingreso al mercado laboral para costear los gastos de su grupo familiar.','True');
INSERT INTO "Respuestas" VALUES (20,5,'Todas son correctas.','False');
INSERT INTO "Respuestas" VALUES (21,6,'$85.000','False');
INSERT INTO "Respuestas" VALUES (22,6,'$63.000','False');
INSERT INTO "Respuestas" VALUES (23,6,'$79.000','True');
INSERT INTO "Respuestas" VALUES (24,6,'$71.000','False');
INSERT INTO "Respuestas" VALUES (25,7,'82,4%','True');
INSERT INTO "Respuestas" VALUES (26,7,'83,1%','False');
INSERT INTO "Respuestas" VALUES (27,7,'84,2%','False');
INSERT INTO "Respuestas" VALUES (28,7,'83,6%','False');
INSERT INTO "Respuestas" VALUES (29,8,'200','False');
INSERT INTO "Respuestas" VALUES (30,8,'180','True');
INSERT INTO "Respuestas" VALUES (31,8,'190','False');
INSERT INTO "Respuestas" VALUES (32,8,'150','False');
INSERT INTO "Respuestas" VALUES (33,9,'10%','False');
INSERT INTO "Respuestas" VALUES (34,9,'5%','False');
INSERT INTO "Respuestas" VALUES (35,9,'1%','False');
INSERT INTO "Respuestas" VALUES (36,9,'3%','True');
INSERT INTO "Respuestas" VALUES (37,10,'99,30%','False');
INSERT INTO "Respuestas" VALUES (38,10,'99,26%','False');
INSERT INTO "Respuestas" VALUES (39,10,'99,00%','True');
INSERT INTO "Respuestas" VALUES (40,10,'99,13%','False');
INSERT INTO "Respuestas" VALUES (41,11,'Falta de computadoras, conexión a internet, recursos pedagógicos de los docentes , y por el distanciamiento social.','True');
INSERT INTO "Respuestas" VALUES (42,11,'Falta de predisposición docente.','False');
INSERT INTO "Respuestas" VALUES (43,11,'Falta de predisposición estudiantil.','False');
INSERT INTO "Respuestas" VALUES (44,11,'Todas son correctas.','False');
INSERT INTO "Respuestas" VALUES (45,12,'Exceso de tareas.','False');
INSERT INTO "Respuestas" VALUES (46,12,'Desestabilidad mental a causa del encierro y las restricciones.','True');
INSERT INTO "Respuestas" VALUES (47,12,'Situación económica difícil.','False');
INSERT INTO "Respuestas" VALUES (48,12,'Ninguna es correcta.','False');
INSERT INTO "Respuestas" VALUES (49,13,'2006','True');
INSERT INTO "Respuestas" VALUES (50,13,'1993','False');
INSERT INTO "Respuestas" VALUES (51,13,'2001','False');
INSERT INTO "Respuestas" VALUES (52,13,'1964','False');
INSERT INTO "Respuestas" VALUES (53,14,'2010','False');
INSERT INTO "Respuestas" VALUES (54,14,'2006','True');
INSERT INTO "Respuestas" VALUES (55,14,'2012','False');
INSERT INTO "Respuestas" VALUES (56,14,'2008','False');
INSERT INTO "Respuestas" VALUES (57,15,'500000','False');
INSERT INTO "Respuestas" VALUES (58,15,'1000000','True');
INSERT INTO "Respuestas" VALUES (59,15,'600000','False');
INSERT INTO "Respuestas" VALUES (60,15,'800000','False');
INSERT INTO "Respuestas" VALUES (61,16,'Colombia','False');
INSERT INTO "Respuestas" VALUES (62,16,'Brasil','True');
INSERT INTO "Respuestas" VALUES (63,16,'Uruguay','False');
INSERT INTO "Respuestas" VALUES (64,16,'Cuba','False');
INSERT INTO "Respuestas" VALUES (65,17,'Dibujos','False');
INSERT INTO "Respuestas" VALUES (66,17,'Comentarios','False');
INSERT INTO "Respuestas" VALUES (67,17,'Chistes','False');
INSERT INTO "Respuestas" VALUES (68,17,'Todas son correctas','True');
INSERT INTO "Respuestas" VALUES (69,18,'Lengua materna','False');
INSERT INTO "Respuestas" VALUES (70,18,'Acceso a recursos','True');
INSERT INTO "Respuestas" VALUES (71,18,'Tipo de piel','False');
INSERT INTO "Respuestas" VALUES (72,18,'Acento','False');
INSERT INTO "Respuestas" VALUES (73,19,'Contar tu historia','False');
INSERT INTO "Respuestas" VALUES (74,19,'Aislar a un compañero que se viste diferente','True');
INSERT INTO "Respuestas" VALUES (75,19,'Escuchar a los demás.','False');
INSERT INTO "Respuestas" VALUES (76,19,'Educarse','False');
INSERT INTO "Respuestas" VALUES (77,20,'Evita despreciar las ideas y creencias de la otra persona.','False');
INSERT INTO "Respuestas" VALUES (78,20,'Escucha el punto de vista del otro.','False');
INSERT INTO "Respuestas" VALUES (79,20,'Mantén la calma. ','False');
INSERT INTO "Respuestas" VALUES (80,20,'Todas son correctas.','True');
INSERT INTO "Respuestas" VALUES (81,21,'12 de octubre','True');
INSERT INTO "Respuestas" VALUES (82,21,'20 de octubre','False');
INSERT INTO "Respuestas" VALUES (83,21,'10 de agosto','False');
INSERT INTO "Respuestas" VALUES (84,21,'29 de agosto','False');
INSERT INTO "Respuestas" VALUES (85,22,'12 de octubre','False');
INSERT INTO "Respuestas" VALUES (86,22,'25 de junio','False');
INSERT INTO "Respuestas" VALUES (87,22,'21 de mayo ','True');
INSERT INTO "Respuestas" VALUES (88,22,'11 de septiembre','False');
INSERT INTO "Respuestas" VALUES (89,23,'“Día del Respeto a la Diversidad de Razas”','False');
INSERT INTO "Respuestas" VALUES (90,23,'“Día de la Raza”','True');
INSERT INTO "Respuestas" VALUES (91,23,'Nunca cambió de nombre','False');
INSERT INTO "Respuestas" VALUES (92,23,'“Día de la conmemoración de las Razas”','False');
INSERT INTO "Respuestas" VALUES (93,24,'Hablé con la/s persona/s que me discriminó/aron.','True');
INSERT INTO "Respuestas" VALUES (94,24,'Me retiré del lugar.','False');
INSERT INTO "Respuestas" VALUES (95,24,'Insulté a la/s persona/s que me discriminó/arond.','False');
INSERT INTO "Respuestas" VALUES (96,24,'Denuncié a la/s persona/s que me discriminó/aron.','False');
INSERT INTO "Respuestas" VALUES (97,25,'Argentina','False');
INSERT INTO "Respuestas" VALUES (98,25,'China','False');
INSERT INTO "Respuestas" VALUES (99,25,'Alemania','False');
INSERT INTO "Respuestas" VALUES (100,25,'Estados Unidos','True');
INSERT INTO "Respuestas" VALUES (101,26,'30.2%','False');
INSERT INTO "Respuestas" VALUES (102,26,'12.5%','False');
INSERT INTO "Respuestas" VALUES (103,26,'8.8%','True');
INSERT INTO "Respuestas" VALUES (104,26,'2.7%','False');
INSERT INTO "Respuestas" VALUES (105,27,'Ámbito educativo','False');
INSERT INTO "Respuestas" VALUES (106,27,'En la Sociedad en general/en cualquier lugar','True');
INSERT INTO "Respuestas" VALUES (107,27,'Eventos sociales (reuniones/fiestas)','False');
INSERT INTO "Respuestas" VALUES (108,27,'Ámbito laboral','False');
INSERT INTO "Respuestas" VALUES (109,28,'18 a 29','False');
INSERT INTO "Respuestas" VALUES (110,28,'30 a 44','True');
INSERT INTO "Respuestas" VALUES (111,28,'45 a 59','False');
INSERT INTO "Respuestas" VALUES (112,28,'60 a 74','False');
INSERT INTO "Respuestas" VALUES (113,29,'10%','False');
INSERT INTO "Respuestas" VALUES (114,29,'24%','False');
INSERT INTO "Respuestas" VALUES (115,29,'40.5%','False');
INSERT INTO "Respuestas" VALUES (116,29,'63%','True');
INSERT INTO "Respuestas" VALUES (117,30,'Comentarios de reprobación','False');
INSERT INTO "Respuestas" VALUES (118,30,'Indiferencia','True');
INSERT INTO "Respuestas" VALUES (119,30,'Intervención directa contra el/la agresor/a','False');
INSERT INTO "Respuestas" VALUES (120,30,'Apoyo al agresora/or','False');
INSERT INTO "Respuestas" VALUES (121,31,'Estudios.','False');
INSERT INTO "Respuestas" VALUES (122,31,'Puestos de empleo.','False');
INSERT INTO "Respuestas" VALUES (123,31,'Posiciones de poder.','False');
INSERT INTO "Respuestas" VALUES (124,31,'En todos los entornos.','True');
INSERT INTO "Respuestas" VALUES (125,32,'Crianza de hijos.','False');
INSERT INTO "Respuestas" VALUES (126,32,'Tareas necesarias para garantizar cuidado y bienestar de las personas que integren su familia.','False');
INSERT INTO "Respuestas" VALUES (127,32,'Docencia.','False');
INSERT INTO "Respuestas" VALUES (128,32,'Todas son correctas.','True');
INSERT INTO "Respuestas" VALUES (129,33,'Cámara de Diputados de la Nación.','False');
INSERT INTO "Respuestas" VALUES (130,33,'Gabinetes de la Nación y las provincias.','False');
INSERT INTO "Respuestas" VALUES (131,33,'Cámara de Senadores de la Nación.','False');
INSERT INTO "Respuestas" VALUES (132,33,'Todas son correctas.','True');
INSERT INTO "Respuestas" VALUES (133,34,'1 de diciembre','True');
INSERT INTO "Respuestas" VALUES (134,34,'3 de diciembre','False');
INSERT INTO "Respuestas" VALUES (135,34,'21 de noviembre','False');
INSERT INTO "Respuestas" VALUES (136,34,'30 de noviembre','False');
INSERT INTO "Respuestas" VALUES (137,35,'Art. 14 bis','False');
INSERT INTO "Respuestas" VALUES (138,35,'Art. 37 y 75','True');
INSERT INTO "Respuestas" VALUES (139,35,'Art. 75','False');
INSERT INTO "Respuestas" VALUES (140,35,'Art. 37','False');
INSERT INTO "Respuestas" VALUES (141,36,'Gran Bretaña ','False');
INSERT INTO "Respuestas" VALUES (142,36,'Islandia','True');
INSERT INTO "Respuestas" VALUES (143,36,'Irlanda','False');
INSERT INTO "Respuestas" VALUES (144,36,'Nueva Zelanda','False');
INSERT INTO "Respuestas" VALUES (145,37,'Alemania','False');
INSERT INTO "Respuestas" VALUES (146,37,'Yemen','False');
INSERT INTO "Respuestas" VALUES (147,37,'República Democrática del Congo','False');
INSERT INTO "Respuestas" VALUES (148,37,'Nigeria','True');
INSERT INTO "Respuestas" VALUES (149,38,'20,5%','False');
INSERT INTO "Respuestas" VALUES (150,38,'26,9%','False');
INSERT INTO "Respuestas" VALUES (151,38,'29,1%','True');
INSERT INTO "Respuestas" VALUES (152,38,'30,4%','False');
INSERT INTO "Respuestas" VALUES (153,39,'3,7%','True');
INSERT INTO "Respuestas" VALUES (154,39,'4,5%','False');
INSERT INTO "Respuestas" VALUES (155,39,'7,9%','False');
INSERT INTO "Respuestas" VALUES (156,39,'5,4%','False');
INSERT INTO "Respuestas" VALUES (157,40,'53','False');
INSERT INTO "Respuestas" VALUES (158,40,'78','False');
INSERT INTO "Respuestas" VALUES (159,40,'129','False');
INSERT INTO "Respuestas" VALUES (160,40,'96','True');
INSERT INTO "Respuestas" VALUES (161,41,'16,8%','True');
INSERT INTO "Respuestas" VALUES (162,41,'18,3%','False');
INSERT INTO "Respuestas" VALUES (163,41,'12,8%','False');
INSERT INTO "Respuestas" VALUES (164,41,'20,1%','False');
INSERT INTO "Respuestas" VALUES (165,42,'42%','False');
INSERT INTO "Respuestas" VALUES (166,42,'8%','False');
INSERT INTO "Respuestas" VALUES (167,42,'17%','False');
INSERT INTO "Respuestas" VALUES (168,42,'33% ','True');
INSERT INTO "Respuestas" VALUES (169,43,'50%','False');
INSERT INTO "Respuestas" VALUES (170,43,'78%','False');
INSERT INTO "Respuestas" VALUES (171,43,'62%','True');
INSERT INTO "Respuestas" VALUES (172,43,'100%','False');
INSERT INTO "Respuestas" VALUES (173,44,'15.7%','False');
INSERT INTO "Respuestas" VALUES (174,44,'4.9%','True');
INSERT INTO "Respuestas" VALUES (175,44,'2.5%','False');
INSERT INTO "Respuestas" VALUES (176,44,'11.6%','False');
INSERT INTO "Respuestas" VALUES (177,45,'2021','True');
INSERT INTO "Respuestas" VALUES (178,45,'2004','False');
INSERT INTO "Respuestas" VALUES (179,45,'2012','False');
INSERT INTO "Respuestas" VALUES (180,45,'2009','False');
COMMIT;
